name: Update GP Availability

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: playwright install chromium

      - name: Run Scraper
        run: python scrape.py

      - name: Commit updated availability
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add availability.json

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Auto update availability"
            git push
          fi
